import type { Job, JobProvider } from "./types";

export const chinaMockJobs: Job[] = [
  {
    id: "1",
    source: "china-mock",
    title: "前端开发工程师",
    company: "上海云杉科技有限公司",
    city: "上海",
    province: "上海",
    salaryMin: 18000,
    salaryMax: 28000,
    salaryText: "18k-28k 元/月",
    educationRequirement: "本科",
    experienceRequirement: 3,
    description: "负责企业招聘平台 Web 前端开发，使用 React、Next.js 和 TypeScript 建设高质量页面与组件。",
    applyUrl: "https://example.com/china/jobs/1",
    publishedAt: "2026-05-18",
  },
  {
    id: "2",
    source: "china-mock",
    title: "高级前端开发工程师",
    company: "北京星图智能科技有限公司",
    city: "北京",
    province: "北京",
    salaryMin: 25000,
    salaryMax: 40000,
    salaryText: "25k-40k 元/月",
    educationRequirement: "本科",
    experienceRequirement: 5,
    description: "负责核心业务前端架构、性能优化和工程化建设，推动设计系统在多个产品线落地。",
    applyUrl: "https://example.com/china/jobs/2",
    publishedAt: "2026-05-16",
  },
  {
    id: "3",
    source: "china-mock",
    title: "后端开发工程师",
    company: "深圳海量数据技术有限公司",
    city: "深圳",
    province: "广东",
    salaryMin: 22000,
    salaryMax: 35000,
    salaryText: "22k-35k 元/月",
    educationRequirement: "本科",
    experienceRequirement: 3,
    description: "负责 Java、Node.js 服务端接口开发、数据建模、搜索服务和高并发业务系统稳定性建设。",
    applyUrl: "https://example.com/china/jobs/3",
    publishedAt: "2026-05-15",
  },
  {
    id: "4",
    source: "china-mock",
    title: "后端研发实习生",
    company: "杭州云启信息技术有限公司",
    city: "杭州",
    province: "浙江",
    salaryMin: 6000,
    salaryMax: 9000,
    salaryText: "6k-9k 元/月",
    educationRequirement: "不限",
    experienceRequirement: 0,
    description: "参与招聘业务后台服务开发和数据接口维护，有导师辅导，适合希望进入互联网研发方向的候选人。",
    applyUrl: "https://example.com/china/jobs/4",
    publishedAt: "2026-05-14",
  },
  {
    id: "5",
    source: "china-mock",
    title: "数据分析师",
    company: "广州数智增长科技有限公司",
    city: "广州",
    province: "广东",
    salaryMin: 15000,
    salaryMax: 23000,
    salaryText: "15k-23k 元/月",
    educationRequirement: "本科",
    experienceRequirement: 1,
    description: "使用 SQL、Python 和 BI 工具分析用户增长、职位转化和投放效果，输出业务分析报告。",
    applyUrl: "https://example.com/china/jobs/5",
    publishedAt: "2026-05-12",
  },
  {
    id: "6",
    source: "china-mock",
    title: "资深数据分析专家",
    company: "北京北辰数据服务有限公司",
    city: "北京",
    province: "北京",
    salaryMin: 30000,
    salaryMax: 45000,
    salaryText: "30k-45k 元/月",
    educationRequirement: "硕士",
    experienceRequirement: 5,
    description: "负责招聘供需、用户画像和推荐策略分析，搭建指标体系并推动业务决策优化。",
    applyUrl: "https://example.com/china/jobs/6",
    publishedAt: "2026-05-10",
  },
  {
    id: "7",
    source: "china-mock",
    title: "产品经理",
    company: "深圳职达网络科技有限公司",
    city: "深圳",
    province: "广东",
    salaryMin: 20000,
    salaryMax: 32000,
    salaryText: "20k-32k 元/月",
    educationRequirement: "本科",
    experienceRequirement: 3,
    description: "负责招聘匹配产品规划、求职者路径优化、需求拆解、用户调研和跨团队项目推进。",
    applyUrl: "https://example.com/china/jobs/7",
    publishedAt: "2026-05-08",
  },
  {
    id: "8",
    source: "china-mock",
    title: "高级产品经理",
    company: "上海灵犀人力科技有限公司",
    city: "上海",
    province: "上海",
    salaryMin: 28000,
    salaryMax: 42000,
    salaryText: "28k-42k 元/月",
    educationRequirement: "本科",
    experienceRequirement: 5,
    description: "负责企业端招聘 SaaS 产品，从岗位发布、简历筛选到智能匹配全链路体验设计。",
    applyUrl: "https://example.com/china/jobs/8",
    publishedAt: "2026-05-06",
  },
  {
    id: "9",
    source: "china-mock",
    title: "用户运营专员",
    company: "成都启航人力资源有限公司",
    city: "成都",
    province: "四川",
    salaryMin: 9000,
    salaryMax: 14000,
    salaryText: "9k-14k 元/月",
    educationRequirement: "大专",
    experienceRequirement: 1,
    description: "负责求职者社群运营、活动策划、职位内容维护和用户反馈跟进。",
    applyUrl: "https://example.com/china/jobs/9",
    publishedAt: "2026-05-04",
  },
  {
    id: "10",
    source: "china-mock",
    title: "内容运营经理",
    company: "杭州青橙互联网有限公司",
    city: "杭州",
    province: "浙江",
    salaryMin: 16000,
    salaryMax: 26000,
    salaryText: "16k-26k 元/月",
    educationRequirement: "本科",
    experienceRequirement: 3,
    description: "负责招聘内容策略、行业专题、职位推荐栏目和转化数据复盘。",
    applyUrl: "https://example.com/china/jobs/10",
    publishedAt: "2026-05-03",
  },
  {
    id: "11",
    source: "china-mock",
    title: "企业客户销售",
    company: "广州企服增长科技有限公司",
    city: "广州",
    province: "广东",
    salaryMin: 10000,
    salaryMax: 18000,
    salaryText: "10k-18k 元/月",
    educationRequirement: "大专",
    experienceRequirement: 1,
    description: "面向企业客户销售招聘服务产品，负责商机跟进、方案讲解、合同推进和客户维护。",
    applyUrl: "https://example.com/china/jobs/11",
    publishedAt: "2026-05-01",
  },
  {
    id: "12",
    source: "china-mock",
    title: "高级销售经理",
    company: "成都蓝海企业服务有限公司",
    city: "成都",
    province: "四川",
    salaryMin: 18000,
    salaryMax: 30000,
    salaryText: "18k-30k 元/月",
    educationRequirement: "不限",
    experienceRequirement: 5,
    description: "负责区域企业客户拓展、重点客户经营和销售团队目标达成。",
    applyUrl: "https://example.com/china/jobs/12",
    publishedAt: "2026-04-29",
  },
];

export const chinaMockProvider: JobProvider = {
  source: "china-mock",
  searchJobs() {
    return chinaMockJobs;
  },
  getJobById(id) {
    return chinaMockJobs.find((job) => job.id === id);
  },
};
